/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atm_machine;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Lenovo
 */
public class FASTCASH_PAGE extends javax.swing.JFrame {

    /**
     * Creates new form FASTCASH_PAGE
     */
    String accountnumber;
    public FASTCASH_PAGE(String accountnumber) {
        this.accountnumber=accountnumber;
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Rupees100 = new javax.swing.JButton();
        Rupees1000 = new javax.swing.JButton();
        Rupees2000 = new javax.swing.JButton();
        Rupees500 = new javax.swing.JButton();
        Rupees5000 = new javax.swing.JButton();
        Rupees10000 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("XYZ BANK");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Choose your Transaction Type");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Rupees100.setBackground(new java.awt.Color(204, 255, 255));
        Rupees100.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Rupees100.setForeground(new java.awt.Color(0, 51, 51));
        Rupees100.setText("Rs. 100");
        Rupees100.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Rupees100.setMaximumSize(new java.awt.Dimension(127, 23));
        Rupees100.setMinimumSize(new java.awt.Dimension(127, 23));
        Rupees100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rupees100ActionPerformed(evt);
            }
        });

        Rupees1000.setBackground(new java.awt.Color(204, 255, 255));
        Rupees1000.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Rupees1000.setForeground(new java.awt.Color(0, 51, 51));
        Rupees1000.setText("Rs. 1000");
        Rupees1000.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Rupees1000.setMaximumSize(new java.awt.Dimension(127, 23));
        Rupees1000.setMinimumSize(new java.awt.Dimension(127, 23));
        Rupees1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rupees1000ActionPerformed(evt);
            }
        });

        Rupees2000.setBackground(new java.awt.Color(204, 255, 255));
        Rupees2000.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Rupees2000.setForeground(new java.awt.Color(0, 51, 51));
        Rupees2000.setText("Rs. 2000");
        Rupees2000.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Rupees2000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rupees2000ActionPerformed(evt);
            }
        });

        Rupees500.setBackground(new java.awt.Color(204, 255, 255));
        Rupees500.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Rupees500.setForeground(new java.awt.Color(0, 51, 51));
        Rupees500.setText("Rs. 500");
        Rupees500.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Rupees500.setMaximumSize(new java.awt.Dimension(127, 23));
        Rupees500.setMinimumSize(new java.awt.Dimension(127, 23));
        Rupees500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rupees500ActionPerformed(evt);
            }
        });

        Rupees5000.setBackground(new java.awt.Color(204, 255, 255));
        Rupees5000.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Rupees5000.setForeground(new java.awt.Color(0, 51, 51));
        Rupees5000.setText("Rs. 5000");
        Rupees5000.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Rupees5000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rupees5000ActionPerformed(evt);
            }
        });

        Rupees10000.setBackground(new java.awt.Color(204, 255, 255));
        Rupees10000.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Rupees10000.setForeground(new java.awt.Color(0, 51, 51));
        Rupees10000.setText("Rs.10000");
        Rupees10000.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Rupees10000.setMaximumSize(new java.awt.Dimension(127, 23));
        Rupees10000.setMinimumSize(new java.awt.Dimension(127, 23));
        Rupees10000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rupees10000ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(204, 255, 255));
        jButton13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(0, 51, 51));
        jButton13.setText("LOGOUT");
        jButton13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        backButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 51, 51));
        backButton.setText("BACK");
        backButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Rupees2000, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(Rupees100, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(79, 79, 79)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Rupees1000, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Rupees5000, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(91, 91, 91)
                                    .addComponent(Rupees500, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Rupees10000, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(79, 79, 79)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rupees100, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rupees500, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rupees1000, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rupees2000, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rupees5000, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rupees10000, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
        
    
    private void Rupees1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rupees1000ActionPerformed
         try{
                    connect con=new connect();
                    SignIn_Page sgp=new SignIn_Page();
                     
                    double balance=0;
                    
                    ResultSet rs=con.s.executeQuery("select Total_Balance from custumer_details where Account_No='"+accountnumber+"' ");
                    if(rs.next()){
                        balance=rs.getDouble("Total_Balance");
                    }
                    
                    java.util.Date javaDate=new java.util.Date();
                    java.sql.Date sqlDate=new java.sql.Date(javaDate.getTime());
                    
                     balance= balance-1000;
                    PreparedStatement ps=null;
                    ps=con.c.prepareStatement("update custumer_details set Total_Balance='"+balance+"' where Account_No='"+accountnumber+"'  ");
                    ps.executeUpdate();
                    
                    ps=con.c.prepareStatement("insert into transaction_detail (Account_No, date,type,amount,total_amount)Values('"+accountnumber+"' , '"+sqlDate+"' , 'Withdraw' , '100' , '"+balance+"' )");
                    ps.executeUpdate();
                    
                    System.out.println("Successful");
                    
                    con.c.close();
                    
            }catch(Exception e){
                System.out.println(e);
            }
    }//GEN-LAST:event_Rupees1000ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
        new Services_options("").setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void Rupees100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rupees100ActionPerformed
            try{
                    connect con=new connect();
                    SignIn_Page sgp=new SignIn_Page();
                     
                    double balance=0;
                    
                    ResultSet rs=con.s.executeQuery("select Total_Balance from custumer_details where Account_No='"+accountnumber+"' ");
                    if(rs.next()){
                        balance=rs.getDouble("Total_Balance");
                    }
                    
                    java.util.Date javaDate=new java.util.Date();
                    java.sql.Date sqlDate=new java.sql.Date(javaDate.getTime());
                    
                     balance= balance-100;
                    PreparedStatement ps=null;
                    ps=con.c.prepareStatement("update custumer_details set Total_Balance='"+balance+"' where Account_No='"+accountnumber+"'  ");
                    ps.executeUpdate();
                    
                    ps=con.c.prepareStatement("insert into transaction_detail (Account_No, date,type,amount,total_amount)Values('"+accountnumber+"' , '"+sqlDate+"' , 'Withdraw' , '100' , '"+balance+"' )");
                    ps.executeUpdate();
                    
                    System.out.println("Successful");
                    
                    con.c.close();
                    
            }catch(Exception e){
                System.out.println(e);
            }     
    }//GEN-LAST:event_Rupees100ActionPerformed
            
    private void Rupees500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rupees500ActionPerformed
         try{
                    connect con=new connect();
                    SignIn_Page sgp=new SignIn_Page();
                     
                    double balance=0;
                    
                    ResultSet rs=con.s.executeQuery("select Total_Balance from custumer_details where Account_No='"+accountnumber+"' ");
                    if(rs.next()){
                        balance=rs.getDouble("Total_Balance");
                    }
                    
                    java.util.Date javaDate=new java.util.Date();
                    java.sql.Date sqlDate=new java.sql.Date(javaDate.getTime());
                    
                     balance= balance-500;
                    PreparedStatement ps=null;
                    ps=con.c.prepareStatement("update custumer_details set Total_Balance='"+balance+"' where Account_No='"+accountnumber+"'  ");
                    ps.executeUpdate();
                    
                    ps=con.c.prepareStatement("insert into transaction_detail (Account_No, date,type,amount,total_amount)Values('"+accountnumber+"' , '"+sqlDate+"' , 'Withdraw' , '100' , '"+balance+"' )");
                    ps.executeUpdate();
                    
                    System.out.println("Successful");
                    
                    con.c.close();
                    
            }catch(Exception e){
                System.out.println(e);
            }
    }//GEN-LAST:event_Rupees500ActionPerformed

    private void Rupees5000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rupees5000ActionPerformed
         try{
                    connect con=new connect();
                    SignIn_Page sgp=new SignIn_Page();
                     
                    double balance=0;
                    
                    ResultSet rs=con.s.executeQuery("select Total_Balance from custumer_details where Account_No='"+accountnumber+"' ");
                    if(rs.next()){
                        balance=rs.getDouble("Total_Balance");
                    }
                    
                    java.util.Date javaDate=new java.util.Date();
                    java.sql.Date sqlDate=new java.sql.Date(javaDate.getTime());
                    
                     balance= balance-5000;
                    PreparedStatement ps=null;
                    ps=con.c.prepareStatement("update custumer_details set Total_Balance='"+balance+"' where Account_No='"+accountnumber+"'  ");
                    ps.executeUpdate();
                    
                    ps=con.c.prepareStatement("insert into transaction_detail (Account_No, date,type,amount,total_amount)Values('"+accountnumber+"' , '"+sqlDate+"' , 'Withdraw' , '100' , '"+balance+"' )");
                    ps.executeUpdate();
                    
                    System.out.println("Successful");
                    
                    con.c.close();
                    
            }catch(Exception e){
                System.out.println(e);
            }
    }//GEN-LAST:event_Rupees5000ActionPerformed

    private void Rupees2000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rupees2000ActionPerformed
         try{
                    connect con=new connect();
                    SignIn_Page sgp=new SignIn_Page();
                     
                    double balance=0;
                    
                    ResultSet rs=con.s.executeQuery("select Total_Balance from custumer_details where Account_No='"+accountnumber+"' ");
                    if(rs.next()){
                        balance=rs.getDouble("Total_Balance");
                    }
                    
                    java.util.Date javaDate=new java.util.Date();
                    java.sql.Date sqlDate=new java.sql.Date(javaDate.getTime());
                    
                     balance= balance-2000;
                    PreparedStatement ps=null;
                    ps=con.c.prepareStatement("update custumer_details set Total_Balance='"+balance+"' where Account_No='"+accountnumber+"'  ");
                    ps.executeUpdate();
                    
                    ps=con.c.prepareStatement("insert into transaction_detail (Account_No, date,type,amount,total_amount)Values('"+accountnumber+"' , '"+sqlDate+"' , 'Withdraw' , '100' , '"+balance+"' )");
                    ps.executeUpdate();
                    
                    System.out.println("Successful");
                    
                    con.c.close();
                    
            }catch(Exception e){
                System.out.println(e);
            }
    }//GEN-LAST:event_Rupees2000ActionPerformed

    private void Rupees10000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rupees10000ActionPerformed
         try{
                    connect con=new connect();
                    SignIn_Page sgp=new SignIn_Page();
                     
                    double balance=0;
                    
                    ResultSet rs=con.s.executeQuery("select Total_Balance from custumer_details where Account_No='"+accountnumber+"' ");
                    if(rs.next()){
                        balance=rs.getDouble("Total_Balance");
                    }
                    
                    java.util.Date javaDate=new java.util.Date();
                    java.sql.Date sqlDate=new java.sql.Date(javaDate.getTime());
                    
                     balance= balance-10000;
                    PreparedStatement ps=null;
                    ps=con.c.prepareStatement("update custumer_details set Total_Balance='"+balance+"' where Account_No='"+accountnumber+"'  ");
                    ps.executeUpdate();
                    
                    ps=con.c.prepareStatement("insert into transaction_detail (Account_No, date,type,amount,total_amount)Values('"+accountnumber+"' , '"+sqlDate+"' , 'Withdraw' , '100' , '"+balance+"' )");
                    ps.executeUpdate();
                    
                    System.out.println("Successful");
                    
                    con.c.close();
                    
            }catch(Exception e){
                System.out.println(e);
            }
    }//GEN-LAST:event_Rupees10000ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FASTCASH_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FASTCASH_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FASTCASH_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FASTCASH_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FASTCASH_PAGE("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Rupees100;
    private javax.swing.JButton Rupees1000;
    private javax.swing.JButton Rupees10000;
    private javax.swing.JButton Rupees2000;
    private javax.swing.JButton Rupees500;
    private javax.swing.JButton Rupees5000;
    private javax.swing.JButton backButton;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    
}
